import Config

# Configure your database
config :block_poker, BlockPoker.Repo,
  username: "root",
  password: "",
  hostname: "127.127.126.32",
  database: "block-poker",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :block_poker, Socket.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "M6VO7mMnvGBOCpFlVoniw3u8/Db9Ek3BFHCqJRs9PylCsJFflilIzNMRX6taiUv2",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Origin'ы панели администратора в dev: vite dev-сервер и `vite preview`.
# Список явный, `*` плагин не поддерживает (см. Api.Plugs.AdminCors).
config :block_poker, :admin_origins, [
  "http://localhost:5173",
  "http://127.0.0.1:5173",
  "http://localhost:4173",
  "http://127.0.0.1:4173"
]

# God-mode наблюдения за столами в dev: без него панель не показывает карты
# и вкладки стола у неё нет вовсе. В прод этот флаг не переносится.
config :block_poker, :admin_observer, enabled: true

# Автообновление клиента. В dev файлы лежат в репозитории, а фид смотрит на
# сам же dev-сервер: клиент читает его как обычную внешнюю статику и про то,
# что раздаёт её Phoenix, не знает.
config :block_poker, :client_release,
  current: "0.0.0",
  minimum: "0.0.0",
  feed_url: "http://localhost:4000/client-updates",
  dir: "priv/client_updates"
